### ISSUE TITLE
无法同时与super_player使用

### ISSUE THREAD

**Issue by HongZhiQing** [LiteAVSDK/TRTC_Flutter#55]
错误如下：
![iShot_2022-08-19_17 07 07](https://user-images.githubusercontent.com/37497239/185585654-6d1a4252-b020-4b89-8420-d2696638a6fe.png)

**Comment by c1avie** [comment]
tencent_trtc_cloud和super_player都依赖的哪个版本

**Comment by HongZhiQing** [comment]
> tencent_trtc_cloud和super_player都依赖的哪个版本

依赖的tim_ui_kit_calling_plugin里是v2.2.4, super_player是Professional版

**Comment by c1avie** [comment]
这样依赖是可以使用的
tencent_trtc_cloud: 2.3.4

super_player:
    git:
      url: https://github.com/tencentyun/SuperPlayer
      path: Flutter
      ref: release_pro_v1.0.3

**Comment by c1avie** [comment]
你要用tim_ui_kit_calling_plugin？是一对一通话场景吗

**Comment by HongZhiQing** [comment]
> 你要用tim_ui_kit_calling_plugin？是一对一通话场景吗

是的，tim_ui_kit_calling_plugin里的tencent_trtc_cloud版本太低所导致的

**Comment by c1avie** [comment]
可能要到下周去升级下版本

**Comment by HongZhiQing** [comment]
> 可能要到下周去升级下版本

ok,升级好了再close通知一下

**Comment by lan2000** [comment]
> 

什么时候再升级TXLiteAVSDK_Professional，我看播放器已经到1.0.6了
```
super_player:
  git:
    url: https://github.com/LiteAVSDK/Player_Flutter
    path: Flutter
    ref: release_pro_v1.0.6
```

**Comment by lan2000** [comment]
> 这样依赖是可以使用的 tencent_trtc_cloud: 2.3.4
> 
> super_player: git: url: https://github.com/tencentyun/SuperPlayer path: Flutter ref: release_pro_v1.0.3


这个1.0.3版本，在安卓端，有报错，调试模式，安卓手机播放直播流地址，直接黑屏。

```
super_player:
  git:
    url: https://github.com/LiteAVSDK/Player_Flutter
    path: Flutter
    ref: release_pro_v1.0.3
```

播放直播流报错日志：
```

I/flutter (26331): NoSuchMethodError: The method 'toDouble' was called on null.
I/flutter (26331): Receiver: null
I/flutter (26331): Tried calling: toDouble()

I/flutter (26331): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
I/flutter (26331): #1      TXLivePlayerController._eventHandler (package:super_player/Core/txliveplayer_controller.dart:83:52)
I/flutter (26331): #2      _rootRunUnary (dart:async/zone.dart:1399:47)
I/flutter (26331): #3      _CustomZone.runUnary (dart:async/zone.dart:1300:19)
I/flutter (26331): #4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1209:7)
I/flutter (26331): #5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
I/flutter (26331): #6      _DelayedData.perform (dart:async/stream_impl.dart:515:14)
I/flutter (26331): #7      _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
I/flutter (26331): #8      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
I/flutter (26331): #9      _rootRun (dart:async/zone.dart:1383:47)
I/flutter (26331): #10     _CustomZone.run (dart:async/zone.dart:1293:19)
I/flutter (26331): #11     _CustomZone.runGuarded (dart:async/zone.dart:1201:7)
I/flutter (26331): #12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1241:23)
I/flutter (26331): #13     _rootRun (dart:async/zone.dart:1391:13)
I/flutter (26331): #14     _CustomZone.run (dart:async/zone.dart:1293:19)
I/flutter (26331): #15     _CustomZone.runGuarded (dart:async/zone.dart:1201:7)
I/flutter (26331): #16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1241:23)
I/flutter (26331): #17     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
I/flutter (26331): #18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```

**Comment by lan2000** [comment]
> 这样依赖是可以使用的 tencent_trtc_cloud: 2.3.4
> 
> super_player: git: url: https://github.com/tencentyun/SuperPlayer path: Flutter ref: release_pro_v1.0.3

使用TXLivePlayerController 播放直播流地址

这个1.0.3版本，在安卓端，有报错。



```
super_player:
  git:
    url: https://github.com/LiteAVSDK/Player_Flutter
    path: Flutter
    ref: release_pro_v1.0.3
```

播放直播流报错日志：
```

I/flutter (26331): NoSuchMethodError: The method 'toDouble' was called on null.
I/flutter (26331): Receiver: null
I/flutter (26331): Tried calling: toDouble()

I/flutter (26331): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
I/flutter (26331): #1      TXLivePlayerController._eventHandler (package:super_player/Core/txliveplayer_controller.dart:83:52)
I/flutter (26331): #2      _rootRunUnary (dart:async/zone.dart:1399:47)
I/flutter (26331): #3      _CustomZone.runUnary (dart:async/zone.dart:1300:19)
I/flutter (26331): #4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1209:7)
I/flutter (26331): #5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
I/flutter (26331): #6      _DelayedData.perform (dart:async/stream_impl.dart:515:14)
I/flutter (26331): #7      _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
I/flutter (26331): #8      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
I/flutter (26331): #9      _rootRun (dart:async/zone.dart:1383:47)
I/flutter (26331): #10     _CustomZone.run (dart:async/zone.dart:1293:19)
I/flutter (26331): #11     _CustomZone.runGuarded (dart:async/zone.dart:1201:7)
I/flutter (26331): #12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1241:23)
I/flutter (26331): #13     _rootRun (dart:async/zone.dart:1391:13)
I/flutter (26331): #14     _CustomZone.run (dart:async/zone.dart:1293:19)
I/flutter (26331): #15     _CustomZone.runGuarded (dart:async/zone.dart:1201:7)
I/flutter (26331): #16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.da

**Comment by c1avie** [comment]
这个错误你要找Player_Flutter那边的开发人员看一下

**Comment by lan2000** [comment]
> 

这问题在Player_Flutter 1.0.3 以后版本已经修复，但是tencent_trtc_cloud 和Player_Flutter 一起用的话，只能用Player_Flutter 1.0.3版本，所以tencent_trtc_cloud 什么时候升级TXLiteAVSDK_Professional，以便可以使用更新版本的Player_Flutter

**Comment by lan2000** [comment]
> 这个错误你要找Player_Flutter那边的开发人员看一下

这问题在Player_Flutter 1.0.3 以后版本已经修复，但是tencent_trtc_cloud 和Player_Flutter 一起用的话，只能用Player_Flutter 1.0.3版本，所以tencent_trtc_cloud 什么时候升级TXLiteAVSDK_Professional，以便可以使用更新版本的Player_Flutter
